#' pdf_report
#'
#' PDF report generated by Rmarkdown and knitr
#'
#' @export
pdf_report <- report(class="pdf_report")

add_plot.pdf_report <- function(pdf_report, plot, title = NULL, subtitle = NULL) {
  num_plots <- length(pdf_report$.plots)
  pdf_report$.plots[num_plots+1] <- plot
  pdf_report$.titles[num_plots+1] <- title
  pdf_report$.subtitles[num_plots+1] <- subtitle

  NextMethod()
}

output.pdf_report <- function(pdf_report, preamble = system.file("pdf_report-preamble.Rmd", package = "tessireport")) {

  filename <- tempfile()
  inter_file <- tempfile()
  output_file <- tempfile()
  # write out preamble thru knitr::knit(text) to capture variables
  # write out call render_plots

  rmarkdown::render(filename, output_file = output_file, clean = TRUE)

}

render_plots.pdf_report <- function(pdf_report) {
  for (i in seq(length(pdf_report$.plots))) {
    cat("\\clearpage\n")
    cat(paste("###",.titles[i],"  \n"))
    cat(paste(.subtitles[i],"  \n"))
    print(.plots[i])
  }
}
